createNode transform -n LSystem1;
createNode mesh -n LSystemShape1 -p LSystem1;
sets -add initialShadingGroup LSystemShape1;
createNode LSystemNode -n LSystemNode1;
setAttr LSystemNode1.iIteration 2;
setAttr LSystemNode1.iAngle 20;
setAttr LSystemNode1.iStep 5;
setAttr LSystemNode1.iGrammar -type "string" "E:/Study/Upenn/CIS6600_Advanced_Topics_in_CG/HW2/MayaPlugin_LSystem/plants/simple1.txt";
connectAttr LSystemNode1.OutGeometry LSystemShape1.inMesh;